import assert from "node:assert/strict";
import test from "node:test";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { AgentMediaRegistry } from "./media-registry.js";
import { CodexMediaAdapter } from "./media-codex.js";
import type { MediaAdapter, MediaRequest } from "./media-types.js";
const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=", "base64");
const request: MediaRequest = { requestId: "intent-1", projectId: "original-project", revision: "revision-1", agentId: "codex", capability: "text-to-image", prompt: "生成图片" };
async function fixture(t: {after: (fn:()=>Promise<unknown>)=>unknown}) { const root = await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(), "dianran-media-"))); t.after(() => fs.rm(root, { recursive: true, force: true })); const production = path.join(root, "production"); await fs.mkdir(production); return { root, production, registry: new AgentMediaRegistry(path.join(root, "records")) }; }
test("原生身份、项目及授权目录限定产物，重放不重复且原文件改变不影响副本", async (t) => {
    const { root, production, registry } = await fixture(t); const task = await registry.create(request, production); await registry.bind(task.id, { threadId: "thread", turnId: "turn" }); const file = path.join(production, "result.png"); await fs.writeFile(file, png);
    await assert.rejects(registry.registerArtifact(task.id, { threadId: "other", turnId: "turn", itemId: "item", path: file, kind: "image" }));
    const outside = path.join(root, "private.png"); await fs.writeFile(outside, png); const symlink = path.join(production, "escape.png"); await fs.symlink(outside, symlink);
    await assert.rejects(registry.registerArtifact(task.id, { threadId: "thread", turnId: "turn", itemId: "item", path: symlink, kind: "image" }));
    const input = { threadId: "thread", turnId: "turn", itemId: "item", path: file, kind: "image" as const }; const artifact = await registry.registerArtifact(task.id, input); assert.deepEqual(await registry.registerArtifact(task.id, input), artifact); assert.equal((await registry.get(task.id, request.projectId)).artifacts.length, 1);
    await fs.writeFile(file, "changed"); assert.deepEqual((await registry.readArtifact(task.id, artifact.id, request.projectId)).data, png); await assert.rejects(registry.readArtifact(task.id, artifact.id, "new-focused-project")); assert.equal(JSON.stringify(await registry.get(task.id, request.projectId)).includes(production), false);
});
test("服务重启保留未知任务，不重新提交且损坏版本拒绝覆盖", async (t) => { const { production, registry, root } = await fixture(t); const task = await registry.create(request, production); await registry.bind(task.id, { threadId: "t", turnId: "u" }); const recovered = new AgentMediaRegistry(path.join(root, "records")); await recovered.recover(); assert.equal((await recovered.get(task.id, request.projectId)).status, "unknown"); const file = path.join(root,"records",`${task.id}.json`); const invalid = JSON.stringify({version:99,id:task.id}); await fs.writeFile(file,invalid); await assert.rejects(recovered.recover()); assert.equal(await fs.readFile(file,"utf8"),invalid); });
test("未知工具不自动提交、无视频能力、已确认验证同意图并发只提交一次", async (t) => { const { production, registry } = await fixture(t); let starts=0; let finished!:()=>void; const completion=new Promise<void>((resolve)=>{finished=resolve;}); const adapter = new CodexMediaAdapter(registry,production,async()=>({authenticated:true,imageTool:"unverified"}),async(_,bind)=>{ starts++; await bind("thread","turn"); finished(); }); await assert.rejects(adapter.submit(request)); assert.equal((await adapter.capabilities()).capabilities["text-to-video"],"unavailable"); const confirmed={...request,allowUnverified:true}; const results=await Promise.all([adapter.submit(confirmed),adapter.submit(confirmed)]); assert.equal(results[0].id,results[1].id); assert.equal(starts,1); await completion; await assert.rejects(adapter.submit({...request,parameters:{size:"1024x1024"}})); });
test("第二 Agent 的图片与异步视频使用相同契约登记查询读取", async (t) => { const { production, registry } = await fixture(t); const adapter: MediaAdapter = { async capabilities(){return {agentId:"isolated-fixture",tool:"fixture",backend:"fixture",billing:"无付费",capabilities:{"text-to-image":"verified","text-to-video":"verified"},query:true,cancel:false};}, async submit(input){const task=await registry.create(input,production);await registry.bind(task.id,{threadId:"fake-native",turnId:task.id});return registry.get(task.id,input.projectId);}, query: (id,project)=>registry.get(id,project) };
    for(const kind of ["image","video"] as const){ const input={...request,agentId:"isolated-fixture",requestId:kind,capability:kind==="image"?"text-to-image" as const:"text-to-video" as const}; const task=await adapter.submit(input);assert.equal(task.status,"running");const file=path.join(production,`${kind}.media`); await fs.writeFile(file,kind==="image"?png:Buffer.from("00000018667479706d703432000000006d70343269736f6d", "hex"));const artifact=await registry.registerArtifact(task.id,{threadId:"fake-native",turnId:task.id,itemId:kind,path:file,kind});assert.equal((await adapter.query!(task.id,input.projectId)).status,"completed");assert.equal((await registry.readArtifact(task.id,artifact.id,input.projectId)).artifact.kind,kind); }
});
test("真实事件替身等待原生绑定持久化并将产物归属原项目", async (t) => {
    const { root } = await fixture(t); const { createCodexMediaRuntime } = await import("./media-runtime.js"); let finished!:()=>void; const completion = new Promise<void>((resolve)=>{finished=resolve;}); const events: unknown[]=[];
    const runtime=createCodexMediaRuntime({productionDirectory:path.join(root,"outputs"),recordsDirectory:path.join(root,"runtime-records"),evidence:async()=>({authenticated:true,imageTool:"verified"}),emit:(type,payload)=>{events.push({type,payload});},startThread:async()=>({id:"native-thread"}),runTurn:async(_,emit,attachments,options)=>{assert.equal(attachments.length,0);assert.equal(options.model,"fixture-model");options.onTurn("native-turn");const file=path.join(options.cwd,"native.png");await fs.writeFile(file,png);emit("agent_event",{type:"item.completed",thread_id:"native-thread",turn_id:"native-turn",item:{type:"image_generation",id:"native-item",savedPath:file,status:"completed"}});},onFinish:()=>finished()});
    const task=await runtime.adapter.submit({...request,codexModel:"fixture-model"});await completion;const result=await runtime.registry.get(task.id,request.projectId);assert.equal(result.status,"completed");assert.equal(result.artifacts.length,1);assert.ok(events.some((event:any)=>event.type==="agent_media_artifact" && event.payload.projectId==="original-project"));
});
test("已有侧栏 turn 显式登记归属，不调用生成且完成事件等待登记",async(t)=>{
    const {root,production}=await fixture(t);const {createCodexMediaRuntime}=await import("./media-runtime.js");let imported!:()=>void;const done=new Promise<void>(resolve=>{imported=resolve;});let starts=0;
    const runtime=createCodexMediaRuntime({productionDirectory:production,recordsDirectory:path.join(root,"native-records"),evidence:async()=>({authenticated:true,imageTool:"unverified"}),emit:(type)=>{if(type==="agent_media_artifact")imported();},startThread:async()=>{starts++;return{id:"never"};},runTurn:async()=>{starts++;}});
    const file=path.join(production,"native.png");await fs.writeFile(file,png);const binding=runtime.bindNativeTurn("existing-thread","existing-turn",{...request,cwd:production});runtime.capture("agent_event",{type:"item.completed",thread_id:"existing-thread",turn_id:"existing-turn",item:{type:"image_generation",id:"existing-item",savedPath:file}});await done;await binding;assert.equal(starts,0);const tasks=await runtime.registry.list(request.projectId);assert.equal(tasks.length,1);assert.equal(tasks[0].artifacts.length,1);
});
test("固定原生图片输出安全复制到任务授权目录，原文件删除后仍可读且清除旧提交错误",async(t)=>{
    const {root}=await fixture(t);const {createCodexMediaRuntime}=await import("./media-runtime.js");const codexHome=path.join(root,"codex-home");const sourceDirectory=path.join(codexHome,"generated_images","native-thread");await fs.mkdir(sourceDirectory,{recursive:true});const source=path.join(sourceDirectory,"native-item.png");await fs.writeFile(source,png);let finished!:()=>void;const done=new Promise<void>(resolve=>{finished=resolve;});
    const runtime=createCodexMediaRuntime({productionDirectory:path.join(root,"outputs"),recordsDirectory:path.join(root,"records-fixed"),codexHome,evidence:async()=>({authenticated:true,imageTool:"verified"}),emit:()=>{},startThread:async()=>({id:"native-thread"}),runTurn:async(_,emit,_attachments,options)=>{options.onTurn("native-turn");emit("agent_event",{type:"item.completed",thread_id:"native-thread",turn_id:"native-turn",item:{type:"image_generation",id:"native-item",savedPath:source}});},onFinish:()=>finished()});
    const task=await runtime.adapter.submit({...request,requestId:"fixed-output"});await done;const result=await runtime.registry.get(task.id,request.projectId);assert.equal(result.status,"completed");assert.equal(result.error,undefined);assert.equal(result.artifacts.length,1);await fs.unlink(source);assert.deepEqual((await runtime.registry.readArtifact(task.id,result.artifacts[0].id,request.projectId)).data,png);const production=await runtime.registry.authorizedProductionRoot(task.id);assert.deepEqual(await fs.readFile(path.join(production,"native-item.png")),png);
});
test("原生输出fallback拒绝任意路径、文件符号链接与线程目录符号链接",async(t)=>{
    const {root}=await fixture(t);const {createCodexMediaRuntime}=await import("./media-runtime.js");
    for(const scenario of ["arbitrary-path","file-symlink","thread-symlink"]){await t.test(scenario,async()=>{
        const base=path.join(root,scenario);await fs.mkdir(base);const codexHome=path.join(base,"codex-home");const generated=path.join(codexHome,"generated_images");await fs.mkdir(generated,{recursive:true});const privateDirectory=path.join(base,"private");await fs.mkdir(privateDirectory);const privateFile=path.join(privateDirectory,"native-item.png");await fs.writeFile(privateFile,png);const sourceDirectory=path.join(generated,"native-thread");let source:string;
        if(scenario==="thread-symlink"){await fs.symlink(privateDirectory,sourceDirectory);source=path.join(sourceDirectory,"native-item.png");}else{await fs.mkdir(sourceDirectory);source=scenario==="arbitrary-path"?privateFile:path.join(sourceDirectory,"native-item.png");if(scenario==="file-symlink")await fs.symlink(privateFile,source);}
        let finished!:()=>void;const done=new Promise<void>(resolve=>{finished=resolve;});const runtime=createCodexMediaRuntime({productionDirectory:path.join(base,"outputs"),recordsDirectory:path.join(base,"records"),codexHome,evidence:async()=>({authenticated:true,imageTool:"verified"}),emit:()=>{},startThread:async()=>({id:"native-thread"}),runTurn:async(_,emit,_attachments,options)=>{options.onTurn("native-turn");emit("agent_event",{type:"item.completed",thread_id:"native-thread",turn_id:"native-turn",item:{type:"image_generation",id:"native-item",savedPath:source}});},onFinish:()=>finished()});const task=await runtime.adapter.submit({...request,requestId:scenario});await done;const result=await runtime.registry.get(task.id,request.projectId);assert.equal(result.status,"unknown");assert.equal(result.artifacts.length,0);assert.ok(result.error?.includes("原产物导入失败"));
    });}
});
