import type { ThemeConfig } from "antd";
import { theme as antdTheme } from "antd";
import { BRAND } from "@/constant/brand";

const SANS = '"Noto Sans SC", "PingFang SC", "Microsoft YaHei", system-ui, sans-serif';
const MONO = '"Noto Sans Mono", ui-monospace, "SFMono-Regular", "Cascadia Mono", Menlo, Consolas, monospace';

/** Hex only. antd does not reliably read the CSS variables in tokens.css. */
const palette = {
    light: {
        primary: "#C8402A",
        primaryHover: "#B8321E",
        primaryText: "#FFFFFF",
        text: "#1B1916",
        textSecondary: "#3A362F",
        textTertiary: "#6B645A",
        textQuaternary: "#8C8478",
        container: "#FBF8F2",
        layout: "#F5EFE4",
        fill: "#ECE4D5",
        fillStrong: "#DDD2BF",
        soft: "#F6E3DC",
        line: "#E3DACA",
        info: "#35575E",
        ok: "#4C8B6B",
        warn: "#B7791F",
        danger: "#B8321E",
        link: "#1B1916",
        linkHover: "#3A362F",
    },
    dark: {
        primary: "#D9573D",
        primaryHover: "#EE7A60",
        primaryText: "#FFFFFF",
        text: "#F1EBE0",
        textSecondary: "#D9D1C3",
        textTertiary: "#A69D8F",
        textQuaternary: "#857D71",
        container: "#211E1A",
        layout: "#171512",
        fill: "#2A2621",
        fillStrong: "#3A352E",
        soft: "#3A221C",
        line: "#332E28",
        info: "#9FC2C4",
        ok: "#6FB08E",
        warn: "#D9A441",
        danger: "#EE7A60",
        link: "#F1EBE0",
        linkHover: "#D9D1C3",
    },
} as const;

export function getAntThemeConfig(dark: boolean): ThemeConfig {
    const color = dark ? palette.dark : palette.light;

    return {
        algorithm: dark ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
        cssVar: { key: dark ? `${BRAND.id}-dark` : `${BRAND.id}-light` },
        token: {
            colorPrimary: color.primary,
            colorPrimaryHover: color.primaryHover,
            colorPrimaryActive: color.primaryHover,
            colorPrimaryBg: color.soft,
            colorPrimaryBgHover: color.soft,
            colorPrimaryText: color.primary,
            colorInfo: color.info,
            colorSuccess: color.ok,
            colorWarning: color.warn,
            colorError: color.danger,
            colorText: color.text,
            colorTextBase: color.text,
            colorTextSecondary: color.textSecondary,
            colorTextTertiary: color.textTertiary,
            colorTextQuaternary: color.textQuaternary,
            colorTextLightSolid: color.primaryText,
            colorBgBase: color.layout,
            colorBgContainer: color.container,
            colorBgElevated: color.container,
            colorBgLayout: color.layout,
            colorBorder: color.line,
            colorBorderSecondary: color.line,
            colorSplit: color.line,
            colorFillAlter: color.fill,
            colorFillTertiary: color.fill,
            colorFillSecondary: color.fillStrong,
            colorLink: color.link,
            colorLinkHover: color.linkHover,
            colorLinkActive: color.link,
            controlItemBgHover: color.fill,
            controlItemBgActive: color.soft,
            controlItemBgActiveHover: color.fillStrong,
            controlOutline: "transparent",
            controlOutlineWidth: 2,
            lineWidthFocus: 2,
            borderRadius: 10,
            borderRadiusSM: 6,
            borderRadiusLG: 14,
            fontFamily: SANS,
            fontFamilyCode: MONO,
            fontSize: 14,
            lineHeight: 1.6,
        },
        components: {
            Button: {
                primaryShadow: "none",
            },
            Dropdown: {
                colorBgElevated: color.container,
                colorText: color.text,
                controlItemBgHover: color.fill,
                controlItemBgActive: color.soft,
                controlItemBgActiveHover: color.fillStrong,
            },
            Menu: {
                popupBg: color.container,
                itemActiveBg: color.soft,
                itemHoverBg: color.fill,
                itemSelectedBg: color.soft,
                itemSelectedColor: color.text,
                darkPopupBg: palette.dark.container,
                darkItemHoverBg: palette.dark.fill,
                darkItemSelectedBg: palette.dark.soft,
                darkItemSelectedColor: palette.dark.text,
            },
            Select: {
                optionActiveBg: color.fill,
                optionSelectedBg: color.soft,
                optionSelectedColor: color.text,
                colorBgElevated: color.container,
                colorText: color.text,
            },
            Table: {
                rowSelectedBg: color.soft,
                rowSelectedHoverBg: color.fillStrong,
                colorBgContainer: color.container,
                colorText: color.text,
                borderColor: color.line,
            },
        },
    };
}
