import assert from "node:assert/strict";
import test from "node:test";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import crypto from "node:crypto";
import { execFileSync } from "node:child_process";
import { preparePromptSnapshot } from "../scripts/prepare-prompts.mjs";
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),"dianran-cf-offline-"));t.after(()=>fs.rm(root,{recursive:true,force:true}));const repository=path.join(root,"repo");await fs.mkdir(repository);const source=path.join(repository,"web/public/prompt-sources");await fs.mkdir(source,{recursive:true});await fs.writeFile(path.join(source,"manifest.json"),JSON.stringify({generatedAt:"fixture",sources:[{path:"source.json"}]}));await fs.writeFile(path.join(source,"source.json"),"[]");const git=(args)=>execFileSync("git",["-C",repository,...args]);git(["init","-q"]);git(["add","."]);git(["-c","user.name=Fixture","-c","user.email=fixture@example.invalid","commit","-qm","fixture"]);return{root,repository,source,git};}
test("默认dry-run取确定commit而非工作区，显式离线写包带真实SHA256且不能覆盖",async(t)=>{const {root,repository,source}=await fixture(t);await fs.writeFile(path.join(source,"source.json"),"dirty content must not publish");const report=await preparePromptSnapshot({repository});assert.equal(report.files.find(file=>file.path==="source.json").sha256,crypto.createHash("sha256").update("[]").digest("hex"));assert.deepEqual((await fs.readdir(root)).sort(),["repo"]);const output=path.join(root,"package");const written=await preparePromptSnapshot({repository,output});assert.equal(await fs.readFile(path.join(output,"snapshots",written.commit,"source.json"),"utf8"),"[]");assert.deepEqual(JSON.parse(await fs.readFile(path.join(output,"release-manifest.json"),"utf8")),written);await assert.rejects(preparePromptSnapshot({repository,output}),/EEXIST/);});
test("缺引用文件与Git符号链接拒绝生成包",async(t)=>{const {root,repository,source,git}=await fixture(t);await fs.writeFile(path.join(source,"source.json"),JSON.stringify([{coverUrl:"/prompt-sources/covers/missing.webp"}]));git(["add","."]);git(["-c","user.name=Fixture","-c","user.email=fixture@example.invalid","commit","-qm","missing cover"]);await assert.rejects(preparePromptSnapshot({repository}),/Cover missing/);await fs.writeFile(path.join(source,"source.json"),"[]");await fs.symlink(path.join(root,"private.json"),path.join(source,"private.json"));git(["add","."]);git(["-c","user.name=Fixture","-c","user.email=fixture@example.invalid","commit","-qm","symlink"]);await assert.rejects(preparePromptSnapshot({repository}),/non-regular/);});
test("真实大库JSON超过默认子进程缓冲大小仍可离线校验",async(t)=>{const {repository,source,git}=await fixture(t);const data=JSON.stringify([{prompt:"x".repeat(1_100_000)}]);await fs.writeFile(path.join(source,"source.json"),data);git(["add","."]);git(["-c","user.name=Fixture","-c","user.email=fixture@example.invalid","commit","-qm","large library"]);const report=await preparePromptSnapshot({repository});const entry=report.files.find(file=>file.path==="source.json");assert.equal(entry.bytes,Buffer.byteLength(data));assert.equal(entry.sha256,crypto.createHash("sha256").update(data).digest("hex"));});
