import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';const require=createRequire(import.meta.url),ts=require('typescript');
function fixture(){let state,writer=true,fail=false;const saved=new Map();const tasks=[];const mocks={'@/features/tasks/task-store':{useTaskStore:{getState:()=>({tasks})},beginCreationTask:task=>tasks.push(task),updateCreationTask:(id,patch)=>Object.assign(tasks.find(task=>task.id===id),patch)},localforage:{createInstance:()=>({setItem:async(key,value)=>{if(fail)throw Error('disk full');saved.set(key,structuredClone(value));},iterate:async fn=>{for(const [key,value]of saved)fn(value,key)}})},zustand:{create:fn=>{state=fn();return{getState:()=>state,setState:patch=>{Object.assign(state,typeof patch==='function'?patch(state):patch)}}}},'@/constant/brand':{STORAGE_NS:'test'},'@/lib/write-ownership':{assertBusinessWriter:()=>{if(!writer)throw Error('readonly')}}};const code=ts.transpileModule(readFileSync(new URL('../src/stores/use-agent-media-store.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,module={exports:{}};new Function('require','module','exports',code)(id=>mocks[id],module,module.exports);return{api:module.exports,saved,tasks,state:()=>state,fail:value=>{fail=value},writer:value=>{writer=value}};}
test('browser request intent is durable before paid submission and survives reload separately from task receipts',async()=>{const f=fixture(),request={requestId:'request',projectId:'A',revision:'r',prompt:'poster',agentId:'codex',capability:'text-to-image'};await f.api.recordAgentMediaIntent(request);assert.deepEqual(f.saved.get('intent:request'),request);f.state().intents={};await f.api.reloadAgentMediaReceipts();assert.deepEqual(f.state().intents.request,request);assert.equal(Object.keys(f.state().receipts).length,0);});
test('receipt persistence failure refuses confirmation and concurrent updates preserve previous imports',async()=>{const f=fixture(),task={id:'task',status:'pending',createdAt:1,artifacts:[],request:{requestId:'request',prompt:'poster',codexModel:'model'}};await f.api.recordAgentMediaTask(task);await Promise.all([f.api.recordAgentMediaImport(task,'a',{storageKey:'a',nodeId:'a'}),f.api.recordAgentMediaImport(task,'b',{storageKey:'b',nodeId:'b'})]);assert.deepEqual(Object.keys(f.state().receipts.task.imported).sort(),['a','b']);f.fail(true);await assert.rejects(()=>f.api.recordAgentMediaIntent({requestId:'unsubmitted'}),/disk full/);assert.equal(f.state().intents.unsubmitted,undefined);await assert.rejects(()=>f.api.flushAgentMediaReceipts(),/disk full/);f.writer(false);assert.throws(()=>f.api.recordAgentMediaTask(task),/readonly/);});

test('canvas intent retains task destination after receipt reload',async()=>{
 const f=fixture(),request={requestId:'canvas-request',projectId:'canvas-A',revision:'r',prompt:'poster',agentId:'codex',capability:'text-to-image'};
 await f.api.recordAgentMediaIntent(request,{projectId:'canvas-A',nodeId:'placeholder'});
 await f.api.recordAgentMediaTask({id:'canvas-task',status:'pending',createdAt:1,artifacts:[],request});
 f.state().intents={};await f.api.reloadAgentMediaReceipts();
 assert.equal(f.tasks[0].sourcePath,'/canvas/canvas-A');assert.equal(f.tasks[0].nodeId,'placeholder');
});
