#!/usr/bin/env bash
# [dianran] Weekly prompt-library maintenance (no model test runs; popularity + freshness + on-site usage only).
#   fetch (X, GitHub upstreams, Civitai) -> read usage counts -> merge/score/cleanup -> 点染精选 -> snapshot time
#   -> commit on prompts/YYYY-MM-DD -> push (never forced) -> PR to main with a Chinese changelog.
#   Does not deploy. After the PR merges, run `brand/pipeline/deploy.sh prompts`.
#   App releases are a separate `brand/pipeline/deploy.sh app` to the dianran project.
#
# Usage:  brand/pipeline/run-weekly.sh
# Env:    BASE_BRANCH  branch to start from (default: main)
#         PR_BASE      PR target (default: main)
#         SKIP_PR=1 / SKIP_X=1 for partial runs
# Needs:  node, git, gh (logged in), twscrape-x (logged-in twscrape account),
#         BLOB_READ_WRITE_TOKEN for usage counts (env or ~/.config/dianran/dianran-next.env via `vercel env pull`).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
START=$(date +%s)
DATE="$(TZ=Asia/Taipei date +%F)"
BASE_BRANCH="${BASE_BRANCH:-main}"
PR_BASE="${PR_BASE:-main}"
LOG_DIR="$ROOT/brand/pipeline/candidates"
mkdir -p "$LOG_DIR"
LOG="$LOG_DIR/run-$DATE.log"
exec > >(tee -a "$LOG") 2>&1
# Optional secrets/overrides (e.g. CIVITAI_API_TOKEN, BLOB_READ_WRITE_TOKEN), never committed.
PIPELINE_ENV="${PIPELINE_ENV:-$HOME/.config/dianran/pipeline.env}"
if [ -f "$PIPELINE_ENV" ]; then set -a; . "$PIPELINE_ENV"; set +a; fi
say() { printf '\n[%s] == %s\n' "$(date +%H:%M:%S)" "$*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

for bin in node git gh; do command -v "$bin" >/dev/null || die "$bin not found"; done
[ -z "$(git status --porcelain --untracked-files=no)" ] || die "working tree has uncommitted changes; commit or stash first"

say "branch: prompts/$DATE from origin/$BASE_BRANCH"
git fetch -q origin "$BASE_BRANCH" "$PR_BASE"
BRANCH="prompts/$DATE"
n=2
while git show-ref -q --verify "refs/heads/$BRANCH" || git ls-remote -q --exit-code --heads origin "$BRANCH" >/dev/null 2>&1; do BRANCH="prompts/$DATE-$n"; n=$((n + 1)); done
git checkout -q -b "$BRANCH" "origin/$BASE_BRANCH"
[ -x brand/pipeline/run-weekly.sh ] || die "origin/$BASE_BRANCH has no pipeline (set BASE_BRANCH=prompt-pipeline until it is merged)"
[ -d brand/node_modules/sharp ] || (cd brand && npm ci --no-audit --no-fund)

say "fetch: X"
if [ "${SKIP_X:-}" = "1" ]; then echo "skipped"; rm -f "$LOG_DIR/x.json"; else node brand/pipeline/fetch-x.mjs || { echo "X fetch failed — continuing without X candidates"; rm -f "$LOG_DIR/x.json"; }; fi
say "fetch: GitHub upstreams"
rm -rf "$LOG_DIR/github" "$LOG_DIR/github.json"
node brand/pipeline/fetch-github.mjs || echo "GitHub fetch failed — upstream libraries unchanged"
say "fetch: Civitai"
node brand/pipeline/fetch-civitai.mjs || { echo "Civitai fetch failed — continuing"; rm -f "$LOG_DIR/civitai.json"; }

say "usage counts"
node brand/pipeline/usage-read.mjs
say "merge + score + cleanup"
node brand/pipeline/merge.mjs
say "点染精选"
node brand/pipeline/picks.mjs
say "finalize (prune covers, manifest counts, snapshot time)"
node brand/pipeline/finalize.mjs "$DATE"

say "validate IDs, manifest counts and image references"
node --test brand/pipeline/prompt-key.test.mjs
node brand/pipeline/validate.mjs

ELAPSED=$(( $(date +%s) - START ))
node brand/pipeline/changelog.mjs "$DATE" "$ELAPSED" >/dev/null
REPORT="brand/pipeline/reports/$DATE.md"

say "commit + push"
git add web/public/prompt-sources brand/pipeline/data brand/pipeline/reports
git commit -q -m "chore(prompts): 提示词库周更 $DATE" -m "Generated by brand/pipeline/run-weekly.sh; see $REPORT."
git push -q -u origin "$BRANCH"   # never --force

PR_URL=""
if [ "${SKIP_PR:-}" != "1" ]; then
    say "pull request -> $PR_BASE"
    BODY="$LOG_DIR/pr-body.md"
    if [ "$(wc -c < "$REPORT")" -gt 60000 ]; then
        { sed -n '1,/^## 新增/p' "$REPORT" | sed '$d'; echo "完整清单（新增 / 下架明细）见分支内 \`$REPORT\`。"; echo; sed -n '/^## 点染精选/,$p' "$REPORT"; } > "$BODY"
    else cp "$REPORT" "$BODY"; fi
    if [ "$BASE_BRANCH" != "$PR_BASE" ]; then printf '\n> 注意：本分支基于 `%s`，在它合并到 %s 之前，此 PR 也包含其中尚未合并的提交。\n' "$BASE_BRANCH" "$PR_BASE" >> "$BODY"; fi
    printf '\n合并后执行 `brand/pipeline/deploy.sh prompts` 才会更新 https://dianran.vercel.app 上的提示词。不要部署 dianran-next。\n' >> "$BODY"
    PR_URL=$(gh pr create --base "$PR_BASE" --head "$BRANCH" --title "提示词库周更 $DATE" --body-file "$BODY")
    echo "$PR_URL"
fi

ELAPSED=$(( $(date +%s) - START ))
say "done in $((ELAPSED / 60))m $((ELAPSED % 60))s — branch $BRANCH ${PR_URL:+PR $PR_URL}"
echo "report: $REPORT; log: $LOG"
